<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{70a99225-3558-42f5-a08a-2dc8467b5de3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN

VAR
	fb_HahaDataStuff : FB_DataStuff;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_HahaDataStuff();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>