<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{70a99225-3558-42f5-a08a-2dc8467b5de3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN

VAR
	fb_ObjectOne : FB_DataStuff;
	
	fb_ObjectTwo : FB_DataStuff;
END_VAR

// This uses pass by reference (it is not necessary within a FB)
//   but the implementations could be used in other applications
//   read notes in the other files to see more details.

// Time delays are not implemented in this version
//   so race conditions are not present, and this would be the
//   most ideal situation in terms of multiple functions
//   using the same referenced variable. 
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_ObjectOne();

fb_ObjectTwo();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="20" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>