<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{70a99225-3558-42f5-a08a-2dc8467b5de3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN

VAR
	fb_HahaDataStuff : FB_DataStuff;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_HahaDataStuff();

// This is the pointer implementation of the runners 

// Does not implement delays so there isn't really race conditions, but 
// is a good demonstration of using pointers 
// Although pointers are unecessary in this scenario, the general
// basis can be applied to other scenarios]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="20" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="39" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>